name: Pixel Grinder
favicon: null
layout_spectrum: 0.61807
typography_spectrum: 0.61897
title: Pixel Grinder
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1a1a'
    - '#838484'
    - '#6a6a6b'
    - '#a4a4a4'
    - '#000000'
  brandStrength: 0.09293304244056344
  lightness: 0.9375
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
